django_htmx_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard_view'),
    path('person/', views.PersonListView.as_view(), name='person_list_view'),
    path('person/create/', views.PersonCreateView.as_view(), name='person_create_view'),
    path('person/update/<int:pk>/', views.PersonUpdateView.as_view(), name='person_update_view'),

    path('publisher/', views.PublisherListView.as_view(), name='publisher_list_view'),
    path('publisher/create/', views.PublisherCreateView.as_view(), name='publisher_create_view'),
    path('publisher/update/<int:pk>/', views.PublisherUpdateView.as_view(), name='publisher_update_view'),

    path('book/', views.BookListView.as_view(), name='book_list_view'),
    path('book/create/', views.BookCreateView.as_view(), name='book_create_view'),
    path('book/update/<int:pk>/', views.BookUpdateView.as_view(), name='book_update_view'),

    path('store/', views.StoreListView.as_view(), name='store_list_view'),
    path('store/create/', views.StoreCreateView.as_view(), name='store_create_view'),
    path('store/update/<int:pk>/', views.StoreUpdateView.as_view(), name='store_update_view'),
]

api_urlpatterns = [
    path('api/person/', views.PersonAPIView.as_view(), name='person_api_view'),
    path('api/publisher/', views.PublisherAPIView.as_view(), name='publisher_api_view'),
    path('api/book/', views.BookAPIView.as_view(), name='book_api_view'),
    path('api/store/', views.StoreAPIView.as_view(), name='store_api_view'),
]

htmx_urlpatterns = [
    path('book/create/add-person/', views.AddPersonFormView.as_view(), name='add_person_form_view'),
    path('book/create/add-publisher/', views.AddPublisherFormView.as_view(), name='add_publisher_form_view'),
    path('store/add-book-formset/', views.AddBookFormsetView.as_view(), name='add_book_formset_view'),
    path('store/remove-book-formset/', views.RemoveBookFormsetView.as_view(), name='remove_book_formset_view'),
    path('store/add-book/', views.StoreAddBookFormView.as_view(), name='store_add_book_form_view'),
    path('store/add-person/', views.StoreAddPersonFormView.as_view(), name='store_add_person_form_view'),
    path('store/add-publisher/', views.StoreAddPublisherFormView.as_view(), name='store_add_publisher_form_view'),
]

urlpatterns += htmx_urlpatterns
urlpatterns += api_urlpatterns

myapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
ROLE_CHOICES = [
    ("A", _("Author")),
    ("E", _("Editor")),
]

class AuthorManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role="A")


class EditorManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role="E")


class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    role = models.CharField(max_length=1, choices=ROLE_CHOICES)
    
    objects = models.Manager()  # Default manager
    authors = AuthorManager()
    editors = EditorManager()
    
    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.get_role_display()})"


class Publisher(models.Model):
    name = models.CharField(max_length=300)


class Book(models.Model):
    name = models.CharField(max_length=300)
    pages = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.FloatField()
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    pubdate = models.DateField()

    # Many-to-many relationship with a through model for roles
    persons = models.ManyToManyField(Person)

    def __str__(self):
        return f"{self.name} ({self.pages} pages) - {self.rating} rating"


# class BookPersonRole(models.Model):
#     book = models.ForeignKey(Book, on_delete=models.CASCADE)
#     person = models.ForeignKey(Person, on_delete=models.CASCADE)
#     role = models.CharField(max_length=1, choices=ROLE_CHOICES)


class Store(models.Model):
    name = models.CharField(max_length=300)


class StoreBook(models.Model):
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    price_in_store = models.DecimalField(max_digits=10, decimal_places=2)
    stock_count = models.PositiveIntegerField()

myapp/forms/book.py
# django library imports
from django import forms
from django.forms import formset_factory, inlineformset_factory, modelformset_factory

# crispy forms imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Div, HTML

# project imports
from myapp.models import Book, Person, Publisher

# project forms imports
from myapp.forms.person import PersonForm



# Create your forms here.
class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['id', 'name', 'pages', 'price', 'rating', 'persons', 'publisher', 'pubdate']
        widgets = {
            'pubdate': forms.DateInput(attrs={'type': 'date'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['publisher'].label_from_instance = lambda obj: obj.name

myapp/forms/person.py
# django library imports
from django import forms

# project imports
from myapp.models import Person


# Create your forms here.
class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['first_name', 'last_name', 'role']

myapp/forms/publisher.py
# django library imports
from django import forms

# project imports
from myapp.models import Publisher


# Create your forms here.
class PublisherForm(forms.ModelForm):
    class Meta:
        model = Publisher
        fields = ['name']

myapp/forms/store.py
# django library imports
from django import forms
from django.forms import formset_factory, inlineformset_factory, modelformset_factory

# crispy forms imports
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Div, HTML, Row, Column

# project imports
from myapp.models import Store, StoreBook, Book, Person, Publisher

# project forms imports
from myapp.forms.person import PersonForm



# Create your forms here.
class StoreForm(forms.ModelForm):
    class Meta:
        model = Store
        fields = ['id', 'name']


class StoreBookForm(forms.ModelForm):
    class Meta:
        model = StoreBook
        fields = ['id', 'book', 'price_in_store', 'stock_count']
    
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.helper = FormHelper()
    #     self.helper.layout = Layout(
    #         Row(
    #             Column('book'),
    #             Column('price_in_store'),
    #             Column('stock_count'),
    #         )
    #     )
    


StoreBookFormSet = inlineformset_factory(
    Store,
    StoreBook,
    form=StoreBookForm,
    extra=0,
    min_num=1,
    max_num=3,
    validate_min=True,
    validate_max=True,
    can_delete=True,
)

templates/myapp/book/create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create Book
{% endblock %}

{% block content %}
<h1>Create Book</h1>

{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% for form_error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ form_error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<form action="{% url 'myapp:book_create_view' %}" method="post" novalidate>
    {% csrf_token %}
    
    {% for field in form %}
        {% if field.label == 'Persons' %}
            {{ field|as_crispy_field }}
            <button
                type="button"
                class="btn btn-outline-secondary mb-2"
                hx-get="{% url 'myapp:add_person_form_view' %}"
                hx-target="#offcanvas-here"
                hx-on:click="document.body.style.overflow = 'hidden';document.body.style.paddingRight = '15px';"
            >
                + Add Person
            </button>
        {% elif field.label == 'Publisher' %}
            {{ field|as_crispy_field }}
            <button
                type="button"
                class="btn btn-outline-secondary mb-2"
                hx-get="{% url 'myapp:add_publisher_form_view' %}"
                hx-target="#offcanvas-here"
                hx-on:click="document.body.style.overflow = 'hidden';document.body.style.paddingRight = '15px';"
            >
                + Add Publisher
            </button>
        {% else %}
            {{ field|as_crispy_field }}
        {% endif %}
    {% endfor %}

    <button type="submit" class="btn btn-outline-primary my-2">Save</button>
    <a href="{% url 'myapp:book_list_view' %}" class="btn btn-outline-secondary my-2">Cancel</a>
</form>

<div id="offcanvas-here"></div>

{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Handle offcanvas closing
        document.addEventListener('close_offcanvas', function(event) {
            const element_id = event.detail.element_id;
            const offcanvasElement = document.getElementById(element_id);
            offcanvasElement.innerHTML = '';
            document.body.style.overflow = '';
            document.body.style.paddingRight = '';
        });
    });
</script>
{% endblock %}

templates/myapp/book/index.html
{% extends "base.html" %}

{% block title %}
Book List
{% endblock %}

{% block content %}
<h1>Book List</h1>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}

<div>
    <a href="{% url 'myapp:book_create_view' %}" class="btn btn-outline-primary">Add Book</a>
    <table class="table table-sm table-hover" id="book-datatable">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Pages</th>
                <th scope="col">Price</th>
                <th scope="col">Rating</th>
                <th scope="col">Publisher</th>
                <th scope="col">Pubdate</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        "use strict";
        
        let table = $("#book-datatable").DataTable({
            processing: true,
            serverSide: true,
            responsive: true,
            ajax: {
                url: "{% url 'myapp:book_api_view' %}",  // Backend endpoint
                type: "GET",
            },
            language: {
                lengthMenu: `Display 
                    <select class="form-select form-select-sm mx-1">
                        <option value="5">5</option>
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="50">50</option>
                    </select> books
                `,
            },
            columns: [
                { 
                    data: "id", render: (data, type, row) => {
                        let detailUri = `{% url 'myapp:book_update_view' '0' %}`.replace('0', row.id);
                        return `<a href="${detailUri}">${data}</a>`
                    },
                },
                { data: "name" },
                { data: "pages" },
                { data: "price" },
                { data: "rating" },
                { data: "publisher" },
                { data: "pubdate", width: "150px" },
                { 
                    data: null,
                    orderable: false,
                    width: "150px",
                    render: function (data, type, row) {
                        
                        let editUri = `{% url 'myapp:book_update_view' '0' %}`.replace("0", row.id);
                        
                        return `<div class="btn-group">
                                    <a type="button" class="btn btn-sm btn-outline-primary" href="${editUri}">
                                        <i class="bi bi-pencil font-16 me-1"></i> Edit
                                    </a>
                                </div>`;
                    } 
                },  // Actions column
            ],
            order: [[0, "desc"]],
            stateSave: true,
            "columnDefs": [
                {
                    "targets": '_all',
                    "orderSequence": ["asc", "desc"] // ONLY allow asc/desc
                }
            ],
        });
    });
</script>
{% endblock %}

templates/myapp/book/update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Update Book
{% endblock %}

{% block content %}
<h1>Update Book</h1>


{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% for form_error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ form_error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}


<form action="{% url 'myapp:book_update_view' book.id %}" method="post" novalidate>
    {% csrf_token %}

    {% for field in form %}
        {% if field.label == 'Persons' %}
            {{ field|as_crispy_field }}
            <button
                type="button"
                class="btn btn-outline-secondary mb-2"
                hx-get="{% url 'myapp:add_person_form_view' %}"
                hx-target="#modals-here"
                hx-trigger="click"
                data-bs-toggle="modal"
                data-bs-target="#modals-here"
            >
                + Add Person
            </button>
        {% elif field.label == 'Publisher' %}
            {{ field|as_crispy_field }}
            <button
                type="button"
                class="btn btn-outline-secondary mb-2"
                hx-get="{% url 'myapp:add_publisher_form_view' %}"
                hx-target="#modals-here"
                hx-trigger="click"
                data-bs-toggle="modal"
                data-bs-target="#modals-here"
            >
                + Add Publisher
            </button>
        {% else %}
            {{ field|as_crispy_field }}
        {% endif %}
    {% endfor %}
    <button type="submit" class="btn btn-outline-primary my-2">Save</button>
    <a href="{% url 'myapp:book_list_view' %}" class="btn btn-outline-secondary my-2">Cancel</a>
</form>

<div id="modals-here"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    class="modal fade"
    aria-labelledby="modalHereLabel"
    aria-hidden="true"
    style="display: none"
    tabindex="-1">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content"></div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const modalElement = document.getElementById('modals-here');
        const modal = bootstrap.Modal.getOrCreateInstance(modalElement);
        // const modal = new bootstrap.Modal(modalElement);
        
        // Handle modal closing
        document.addEventListener('closemodal', function() {
            console.log(modal._isShown);
            // modalElement.setAttribute('aria-hidden', 'true');
            // modalElement.removeAttribute('aria-modal');
            // modalElement.removeAttribute('tabindex');
            
            // Handle modal hidden
            modal.hide();
        });
    });
</script>
{% endblock %}

templates/myapp/index.html
{% extends 'base.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block content %}
<h1>Dashboard</h1>
<p>Welcome to the dashboard</p>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock %}


{% block scripts %}
<script>
    console.log("Hello World: Dashboard");
</script>
{% endblock %}

templates/myapp/person/create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create Person
{% endblock %}

{% block content %}
<h1>Create Person</h1>

{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% for form_error in form.non_field_errors %}
<div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ form_error }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

<form action="{% url 'myapp:person_create_view' %}" method="post" novalidate>
    {% csrf_token %}
    {% for field in form %}
        {{ field|as_crispy_field }}
    {% endfor %}
    <button type="submit" class="btn btn-outline-primary my-2">Save</button>
    <a href="{% url 'myapp:person_list_view' %}" class="btn btn-outline-secondary my-2">Cancel</a>
</form>
{% endblock %}

templates/myapp/store/create_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Create Store
{% endblock %}

{% block content %}
<h1>Create Store</h1>

{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% for form_error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ form_error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<form action="{% url 'myapp:store_create_view' %}" method="post" novalidate>
    {% csrf_token %}
    {% for field in form %}
        {{ field|as_crispy_field }}
    {% endfor %}
    <div id="add-book-formset-container">
        {% include "myapp/store/partials/add_book_formset.html" with formset=formset %}
    </div>
    <div>
        <button
            type="button"
            class="btn btn-outline-primary my-2"
            id="add-book-formset-button"
            hx-post="{% url 'myapp:add_book_formset_view' %}"
            hx-target="#add-book-formset-container"
            hx-swap="innerHTML"
            hx-indicator="#loading-spinner"
        >
            +Add More Items
        </button>
    </div>
    <button type="submit" class="btn btn-outline-primary my-2">Save</button>
    <a href="{% url 'myapp:store_list_view' %}" class="btn btn-outline-secondary my-2">Cancel</a>
</form>

<div id="offcanvas-here"></div>
{% endblock %}

{% block scripts %}

<script>
    // ✅ Define globally so HTMX can call it
    function openAddBookWindow(prefix) {
        console.log("prefix",prefix);
        const url = `{% url 'myapp:store_add_book_form_view' %}?target_formset=${prefix}`;  // OR use URL from Django template
        window.open(url, 'AddBookWindow', 'resizable=no,width=800,height=600');
        // window.open(url, 'AddBookWindow', 'width=800,height=600');
    }

    document.addEventListener('DOMContentLoaded', function() {
        // Handle offcanvas closing
        document.addEventListener('close_offcanvas', function(event) {
            const element_id = event.detail.element_id;
            const offcanvasElement = document.getElementById(element_id);
            offcanvasElement.innerHTML = '';
            if(element_id == 'offcanvas-here') {
                document.body.style.overflow = '';
                document.body.style.paddingRight = '';
            }
        });

        // Handle add_book_option_tag custom event
        document.body.addEventListener('add_book_option_tag', function(event) {
            let optionHTML = event.detail.option_tag;
            console.log("optionHTML",optionHTML);

            // Remove 'selected' attribute from the option tag
            optionHTML = optionHTML.replace(/\s+selected(=["']?[^"'\s>]*)?/i, '');
            

            // Append optionHTML directly to all relevant <select> elements
            document.querySelectorAll('select[id^="id_storebook_set-"][id$="-book"]').forEach(select => {
                // Skip if option with same value already exists
                if (!select.querySelector(`option[value="${getOptionValue(optionHTML)}"]`)) {

                    select.insertAdjacentHTML('beforeend', optionHTML);
                }
            });

            // Helper function to extract value from option tag string
            function getOptionValue(optionHTML) {
                const match = optionHTML.match(/value=["']?([^"'>\s]+)/i);
                return match ? match[1] : '';
            }
        });


        // Handle add_person_option_tag custom event
        document.body.addEventListener('add_person_option_tag', function(event) {
            console.log("event.detail",event.detail);
            
            let target_formset = event.detail.target_formset;
            let optionHTML = event.detail.option_tag;
            console.log("target_formset",target_formset);
            console.log("optionHTML",optionHTML);

            const target_formset_element = document.getElementById(`#${target_formset}`);
            target_formset_element.click();

            // Remove 'selected' attribute from the option tag
            // optionHTML = optionHTML.replace(/\s+selected(=["']?[^"'\s>]*)?/i, '');
            

            // Append optionHTML directly to all relevant <select> elements
            document.querySelectorAll('#id_persons').forEach(select => {
                // Skip if option with same value already exists
                if (!select.querySelector(`option[value="${getOptionValue(optionHTML)}"]`)) {

                    select.insertAdjacentHTML('beforeend', optionHTML);
                }
            });

            // Helper function to extract value from option tag string
            function getOptionValue(optionHTML) {
                const match = optionHTML.match(/value=["']?([^"'>\s]+)/i);
                return match ? match[1] : '';
            }
        });


        document.addEventListener('update_formset_button', function() {
            console.log('update_formset_count');
            const formsetCount = document.getElementById(`id_{{formset.prefix}}-TOTAL_FORMS`);
            const formsetMaxCount = document.getElementById(`id_{{formset.prefix}}-MAX_NUM_FORMS`);
            const addBookFormButton = document.getElementById('add-book-formset-button');
            
            if (formsetCount.value < formsetMaxCount.value) {
                addBookFormButton.disabled = false;
            } else {
                addBookFormButton.disabled = true;
            }
        });

        // Dispatch the custom event on DOMContentLoaded
        const event = new Event('update_formset_button');
        document.dispatchEvent(event);
    });
</script>
{% endblock %}

templates/myapp/store/update_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
Update Store
{% endblock %}

{% block content %}
<h1>Update Store</h1>

{% for message in messages %}
<div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}

{% for form_error in form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ form_error }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

<form action="{% url 'myapp:store_update_view' object.id %}" method="post" novalidate>
    {% csrf_token %}
    {% for field in form %}
        {{ field|as_crispy_field }}
    {% endfor %}
    <div id="add-book-formset-container">
        {% include "myapp/store/partials/add_book_formset.html" with formset=formset object=object %}
    </div>
    <div>
        <button
            type="button"
            class="btn btn-outline-primary my-2"
            id="add-book-formset-button"
            hx-post="{% url 'myapp:add_book_formset_view' %}"
            hx-target="#add-book-formset-container"
            hx-swap="innerHTML"
            hx-indicator="#loading-spinner"
        >
            +Add More Items
        </button>
    </div>
    <button type="submit" class="btn btn-outline-primary my-2">Save</button>
    <a href="{% url 'myapp:store_list_view' %}" class="btn btn-outline-secondary my-2">Cancel</a>
</form>

<div id="offcanvas-here"></div>
{% endblock %}

{% block scripts %}

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Handle offcanvas closing
        document.addEventListener('close_offcanvas', function(event) {
            const element_id = event.detail.element_id;
            const offcanvasElement = document.getElementById(element_id);
            offcanvasElement.innerHTML = '';
            if(element_id == 'offcanvas-here') {
                document.body.style.overflow = '';
                document.body.style.paddingRight = '';
            }
        });

        // Handle add_book_option_tag custom event
        document.body.addEventListener('add_book_option_tag', function(event) {
            let optionHTML = event.detail.option_tag;
            console.log("optionHTML",optionHTML);

            // Remove 'selected' attribute from the option tag
            optionHTML = optionHTML.replace(/\s+selected(=["']?[^"'\s>]*)?/i, '');
            

            // Append optionHTML directly to all relevant <select> elements
            document.querySelectorAll('select[id^="id_storebook_set-"][id$="-book"]').forEach(select => {
                // Skip if option with same value already exists
                if (!select.querySelector(`option[value="${getOptionValue(optionHTML)}"]`)) {

                    select.insertAdjacentHTML('beforeend', optionHTML);
                }
            });

            // Helper function to extract value from option tag string
            function getOptionValue(optionHTML) {
                const match = optionHTML.match(/value=["']?([^"'>\s]+)/i);
                return match ? match[1] : '';
            }
        });


        // Handle add_person_option_tag custom event
        document.body.addEventListener('add_person_option_tag', function(event) {
            console.log("event.detail",event.detail);
            
            let target_formset = event.detail.target_formset;
            let optionHTML = event.detail.option_tag;
            console.log("target_formset",target_formset);
            console.log("optionHTML",optionHTML);

            const target_formset_element = document.getElementById(`#${target_formset}`);
            target_formset_element.click();

            // Remove 'selected' attribute from the option tag
            // optionHTML = optionHTML.replace(/\s+selected(=["']?[^"'\s>]*)?/i, '');
            

            // Append optionHTML directly to all relevant <select> elements
            document.querySelectorAll('#id_persons').forEach(select => {
                // Skip if option with same value already exists
                if (!select.querySelector(`option[value="${getOptionValue(optionHTML)}"]`)) {

                    select.insertAdjacentHTML('beforeend', optionHTML);
                }
            });

            // Helper function to extract value from option tag string
            function getOptionValue(optionHTML) {
                const match = optionHTML.match(/value=["']?([^"'>\s]+)/i);
                return match ? match[1] : '';
            }
        });


        document.addEventListener('update_formset_button', function() {
            console.log('update_formset_count');
            const formsetCount = document.getElementById(`id_{{formset.prefix}}-TOTAL_FORMS`);
            const formsetMaxCount = document.getElementById(`id_{{formset.prefix}}-MAX_NUM_FORMS`);
            const addBookFormButton = document.getElementById('add-book-formset-button');
            
            if (formsetCount.value < formsetMaxCount.value) {
                addBookFormButton.disabled = false;
            } else {
                addBookFormButton.disabled = true;
            }
        });

        // Dispatch the custom event on DOMContentLoaded
        const event = new Event('update_formset_button');
        document.dispatchEvent(event);
    });
</script>
{% endblock %}

templates/navbar.html
<nav class="navbar fixed-top" style="background-color: #e3f2fd;" data-bs-theme="light">
    <div class="container-fluid">
        <div class="d-flex">
            <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar"
            aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a href="{% url 'myapp:dashboard_view' %}" class="mx-3 h4 navbar-brand">Django HTMX</a>
        </div>
        <!-- <a class="navbar-brand" href="#">Offcanvas navbar</a> -->
        <div class="offcanvas offcanvas-start" data-bs-backdrop="static" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Django HTMX</h5>
                <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body">
                <ul class="navbar-nav justify-content-start flex-grow-1 pe-3">
                    <li class="nav-item">
                        <a href="{% url 'myapp:person_list_view' %}" class="nav-link {{ person_nav }}" aria-current="page">Person</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'myapp:publisher_list_view' %}" class="nav-link {{ publisher_nav }}" aria-current="page">Publisher</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'myapp:book_list_view' %}" class="nav-link {{ book_nav }}" aria-current="page">Book</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'myapp:store_list_view' %}" class="nav-link {{ store_nav }}" aria-current="page">Store</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>